services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: markapdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  app:
    build: .  # Esto indica que Docker debe construir la imagen usando el Dockerfile en el directorio actual
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/markapdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
    ports:
      - "8080:8080"