INSERT INTO Categories (nombre_categoria) VALUES ('Figuras de Acción');
INSERT INTO Categories (nombre_categoria) VALUES ('Cómics y Mangas');
INSERT INTO Categories (nombre_categoria) VALUES ('Monedas y Billetes');
INSERT INTO Categories (nombre_categoria) VALUES ('Autógrafos');
INSERT INTO Categories (nombre_categoria) VALUES ('Juguetes Vintage');
INSERT INTO Categories (nombre_categoria) VALUES ('Cartas Coleccionables');
INSERT INTO Categories (nombre_categoria) VALUES ('Arte');
INSERT INTO Categories (nombre_categoria) VALUES ('Antiguedades');
INSERT INTO Categories (nombre_categoria) VALUES ('Música y Vinilos');
INSERT INTO Categories (nombre_categoria) VALUES ('Libros Raros');
INSERT INTO Categories (nombre_categoria) VALUES ('Relojes y Joyería');
INSERT INTO Categories (nombre_categoria) VALUES ('Fotografía');